/// ios/Runner/AppDelegate.swift — Reference for Google Maps initialization.
///
/// Merge this import and GMSServices line into the AppDelegate.swift
/// generated by `flutter create`.

import Flutter
import UIKit
import GoogleMaps  // ← Add this import

@main
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    // ← Add this line with your actual API key
    GMSServices.provideAPIKey("YOUR_GOOGLE_MAPS_API_KEY")

    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
