name: bag_alert
description: Personal geolocation reminder — never forget your reusable bags.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.2

  # Maps
  google_maps_flutter: ^2.6.1

  # Location & permissions
  geolocator: ^12.0.0
  permission_handler: ^11.3.1

  # Local notifications
  flutter_local_notifications: ^17.2.1

  # Persistent local storage
  shared_preferences: ^2.3.2

  # UUID generation for store IDs
  uuid: ^4.4.2

  # JSON serialization
  json_annotation: ^4.9.0
  geocoding: ^4.0.0
  flutter_map: ^8.3.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/
